Dashboard
rubenausinholaglow/holaglowreact pull request #23
Opened 2023-06-30 08:21 UTC by JordiPuigdo

Add new features in Dashboard

2023-06-30 09:01 UTC, rubenausinholaglow requested changes

2023-06-30 09:01 UTC, rubenausinholaglow commented on src/app/dashboard/welcome/Welcome.tsx
> +  console.log("user" + username);
Console log fuera

2023-06-30 09:01 UTC, rubenausinholaglow commented on src/app/dashboard/welcome/Welcome.tsx
> +  //  <p className='text-2xl'>¡Hola {client.name}!</p>
Codigo comentado fuera

2023-06-30 09:01 UTC, rubenausinholaglow commented on src/app/dashboard/welcome/Welcome.tsx
> +
No pongamos tantos enters innecesarios

2023-07-03 11:12 UTC, lltallada commented on src/app/dashboard/RegistrationForm.tsx
> +    <div id="Registro" className={`w-3/4 ${show ? '' : 'hidden'}`}>
és millor pràctica i es llegeix millor d'aquesta manera, així no es renderitza html si no cal.
{isRegisterVisible && (<div id="Registro"> .... </div> )

2023-07-03 12:57 UTC, rubenausinholaglow commented on .env.production
> +NEXT_PUBLIC_API_LOGIN=https://holaglowcontactsapidev.azurewebsites.net/Contact/Search
En prod las apis son sin el "dev"

2023-07-03 12:57 UTC, rubenausinholaglow commented on .env
> +API_NEWUSER=https://holaglowcontactsapidev.azurewebsites.net/Contact
Esto se llama API_NEWUSER y los otros empiezan por NEXT_
No creo que tenga sentido llamarlo NEXT_, no nos aporta nada, yo los quitaria.
Tambien yo tenia en mente tener una configuracion que fuera por ejemplo CONTACT_API_URL y que fuera https://holaglowcontactsapidev.azurewebsites.net, y luego cada funcion que llame a cada endpoint que le concatene lo que toca, pero sino aqui tenemos la url muchas veces repetidas

2023-07-03 12:57 UTC, rubenausinholaglow commented on src/app/dashboard/TextInputField.tsx
> +const TextInputField: React.FC<TextInputFieldProps> = ({ label, value, onChange }) => {
Esta clase que parece muy generica, no deberia estar fuera de dashboard por si se quiere utilizar en mas sitios?

2023-07-03 12:57 UTC, rubenausinholaglow commented on src/app/dashboard/page.tsx
> +          console.log(data);
Fuera

2023-07-03 12:57 UTC, rubenausinholaglow commented on src/app/dashboard/utils/auth0.ts
> +export default class Auth0 {
No me convence este nombre de Auth0 :S

2023-07-03 14:19 UTC, rubenausinholaglow approved these changes

2023-07-03 14:19 UTC, merged