Dev 649
rubenausinholaglow/holaglowreact pull request #390
Opened 2023-11-10 08:15 UTC by JordiPuigdo

2023-11-10 08:27 UTC, rubenausinholaglow requested changes

2023-11-10 08:27 UTC, rubenausinholaglow commented on .env.development
> +NEXT_PUBLIC_PATIENTS_API=https://localhost:7055/
CUIDAO!

2023-11-10 08:27 UTC, rubenausinholaglow commented on src/app/components/layout/DashboardLayout.tsx
> +  const routePages: any = {
Ya existe un fichero MenuItems que tiene estas configuraciones creo

2023-11-10 08:27 UTC, rubenausinholaglow commented on src/app/components/layout/DashboardLayout.tsx
> +            if (!remoteControl) return true;
Esta funcion queda ya muy grande, separemos cada switch en una funcion separada porfi

2023-11-10 08:27 UTC, rubenausinholaglow commented on src/app/dashboard/(pages)/checkout/components/payment/Payments.tsx
> +    const localBudgetId = localStorage.getItem('BudgetId');
Local storage fuera

2023-11-10 08:27 UTC, rubenausinholaglow commented on src/app/dashboard/(pages)/crisalix/page.tsx
> +      setId(userCrisalix.crisalixUser[0].id);
Aqui podrias utilizar la variable existsCrisalixUser no?

2023-11-10 08:27 UTC, rubenausinholaglow commented on src/app/dashboard/(pages)/remoteControl/Payment/page.tsx
> +    if (!finalBudget && !budgetIdlocal) {
Esto no habiamos dicho al final que quitabamos la verificacion del budgetIdLocal?

2023-11-10 08:27 UTC, rubenausinholaglow commented on src/app/dashboard/(pages)/remoteControl/validate.tsx
> +    /* const result = await ScheduleService.finish(
Quitar codigo comentado

2023-11-10 08:27 UTC, rubenausinholaglow commented on src/app/dashboard/(pages)/remoteControl/validate.tsx
> +            Validar Cita
Cambiamos el nombre por "Finalizar cita"

2023-11-10 08:29 UTC, JordiPuigdo commented on src/app/components/layout/DashboardLayout.tsx
> +  const routePages: any = {
son dos menu items distintos uno de dash y otro de tablet

2023-11-10 09:22 UTC, rubenausinholaglow approved these changes

2023-11-13 09:20 UTC, rubenausinholaglow approved these changes

2023-12-11 10:55 UTC, closed without merging