Dev 1023 - Header con botones
rubenausinholaglow/holaglowreact pull request #539
Opened 2024-01-25 09:37 UTC by KevinNCabrera

2024-01-25 10:24 UTC, rubenausinholaglow requested changes

2024-01-25 10:24 UTC, rubenausinholaglow commented on src/app/crm/components/layout/MainLayoutCRM.tsx
> +      {!hideHeader && <SideNav />}
No creo que sean necesarias estas variables, creo que siempre mostraremos lo mismo en el header y footer no? Esto lo haciamos en dashboard y web para compartir y ocultar o no pero en crm no sera necesario

2024-01-25 10:24 UTC, rubenausinholaglow commented on src/app/crm/layout.tsx
> +import '@fortawesome/fontawesome-free/css/all.css';
Remove

2024-01-25 10:24 UTC, rubenausinholaglow commented on src/app/services/UserService.ts
> +  static async getAllUsers(token : string) : Promise<User[] | undefined> {
Esto iria en el ocntacts service no?

2024-01-25 10:24 UTC, rubenausinholaglow commented on src/app/services/UserService.ts
> +      return undefined;
Bugnsag

2024-01-25 10:26 UTC, JordiPuigdo commented on src/app/services/UserService.ts
> +  static async getAllUsers(token : string) : Promise<User[] | undefined> {
Tenemos una mezcla aquí esta la UserService que llama a la api de Contacts se podría modificar y cambiar user por Contacts

2024-01-26 09:08 UTC, JordiPuigdo approved these changes

2024-01-26 12:17 UTC, closed without merging