DEV-1039 Detalle de Contacto
rubenausinholaglow/holaglowreact pull request #554
Opened 2024-01-30 09:25 UTC by KevinNCabrera

2024-01-30 10:28 UTC, rubenausinholaglow requested changes

2024-01-30 10:28 UTC, rubenausinholaglow commented on src/app/crm/(pages)/contacts/[id]/page.tsx
> +            No se ha encontrado el contacto solicitado
Quizas aquí tiene mas sentido redirigir a /contacts de nuevo no?

2024-01-30 10:28 UTC, rubenausinholaglow commented on src/app/crm/(pages)/contacts/components/cardContact.tsx
> +          {`${firstName} ${lastName} ${secondLastName} (${flowwwToken})`}
No es el flowwwtoken, es un substring del flowwwtoken, fijate en el codigo que habia antes en el crm que creo que lo hacia. Es algo asi como esto: .Substring(0, user.FlowwwToken.Length - 32)

2024-01-30 10:28 UTC, rubenausinholaglow commented on src/app/crm/(pages)/contacts/components/cardContact.tsx
> +              placeholder="Agregar comentarios"
Comentario, en singular

2024-01-30 10:28 UTC, rubenausinholaglow commented on src/app/crm/(pages)/contacts/components/cardContact.tsx
> +              id="comentarios"
Comentario, en singular

2024-01-30 10:47 UTC, KevinNCabrera commented on src/app/crm/(pages)/contacts/components/cardContact.tsx
> +          {`${firstName} ${lastName} ${secondLastName} (${flowwwToken})`}
Ajustando

2024-01-30 11:29 UTC, rubenausinholaglow requested changes

2024-01-30 11:29 UTC, rubenausinholaglow commented on src/app/crm/(pages)/contacts/components/dataTableContact.tsx
> +function DataTableContact({
Porque esto es un datatablecontact y no un datatable que podamos usar para cualquier cosa? Lo veo bastante generico

2024-01-30 11:29 UTC, rubenausinholaglow commented on src/app/crm/utils/mappingColumns.ts
> +      creationDate: dayjs(task.creationDate).format('DD-MM-YYYY HH:mm:ss'),
Metamos este format en un sitio comun y reaprovechemoslo en todos lados please

2024-01-30 11:29 UTC, rubenausinholaglow commented on src/app/crm/utils/mappingColumns.ts
> +      status: task.executions[0].status,
Hablate con @JordiPuigdo porque le pedi que los status sean con colorcito como teniamos antes en el CRM, no se como lo ha gestionado el para el listado de contactos

2024-01-30 13:26 UTC, KevinNCabrera commented on src/app/crm/utils/mappingColumns.ts
> +      status: task.executions[0].status,
Esta fue una primera iteracion para el tema de los estado luego voy a manejarlo como esta en el crm con un enum y un switch

2024-01-30 13:26 UTC, KevinNCabrera commented on src/app/crm/utils/mappingColumns.ts
> +      creationDate: dayjs(task.creationDate).format('DD-MM-YYYY HH:mm:ss'),
Muy bien

2024-01-31 13:11 UTC, rubenausinholaglow requested changes

2024-01-31 13:11 UTC, rubenausinholaglow commented on src/app/crm/(pages)/contacts/[id]/ContactDetailPageBase.tsx
> +            Agente: {contactDetail.agent.username}
Esto hay que controlar que no sea null, un contacto puede no tener agente asignado

2024-01-31 13:11 UTC, rubenausinholaglow commented on src/app/crm/types/ContactAppointmentsEnum.ts
> +enum AppointmentStatusEnum {
![image](https://github.com/rubenausinholaglow/holaglowreact/assets/134280470/330a58cc-e1e0-4a2c-8d2e-b66e49098940)
Pon los mismos nombres y valores que en backend porfi

2024-01-31 13:11 UTC, rubenausinholaglow commented on src/app/crm/utils/mappingColumns.ts
> +      creationDate: dayjs(task.creationDate).format('DD-MM-YYYY HH:mm:ss'),
Esto sigue pendiente

2024-01-31 13:11 UTC, rubenausinholaglow commented on src/app/crm/utils/mappingColumns.ts
> +export const mappingCalls = (contactDetailCalls: any) => {
No entiendo muy biene sta funcion, si no haces ningun tipo de transformacion

2024-01-31 13:11 UTC, rubenausinholaglow commented on src/app/crm/utils/mappingColumns.ts
> +      treatments: appointment.appointmentProducts[0].product.title,
Aqui hay que iterar sobre todos los appointmentproducts concaternarlos.

2024-02-01 15:24 UTC, KevinNCabrera commented on src/app/crm/utils/mappingColumns.ts
> +      treatments: appointment.appointmentProducts[0].product.title,
Done

2024-02-01 15:24 UTC, KevinNCabrera commented on src/app/crm/utils/mappingColumns.ts
> +export const mappingCalls = (contactDetailCalls: any) => {
Resolved

2024-02-02 11:31 UTC, KevinNCabrera commented on src/app/crm/utils/mappingColumns.ts
> +      creationDate: dayjs(task.creationDate).format('DD-MM-YYYY HH:mm:ss'),
Done!

2024-02-02 11:31 UTC, KevinNCabrera commented on src/app/crm/(pages)/contacts/[id]/ContactDetailPageBase.tsx
> +            Agente: {contactDetail.agent.username}
Done!

2024-02-02 11:38 UTC, KevinNCabrera commented on src/app/crm/types/ContactAppointmentsEnum.ts
> +enum AppointmentStatusEnum {
Done!

2024-02-02 11:42 UTC, KevinNCabrera commented on src/app/crm/utils/mappingColumns.ts
> +      status: task.executions[0].status,
Done!

2024-02-05 08:51 UTC, KevinNCabrera commented on src/app/crm/(pages)/contacts/components/dataTableContact.tsx
> +function DataTableContact({
Listo! Se ha movido el componente a uno generico

2024-02-05 10:49 UTC, rubenausinholaglow approved these changes

2024-02-05 10:49 UTC, merged