Dev 1022
rubenausinholaglow/holaglowreact pull request #558
Opened 2024-01-30 11:57 UTC by JordiPuigdo

2024-01-30 14:34 UTC, rubenausinholaglow requested changes

2024-01-31 13:19 UTC, rubenausinholaglow requested changes

2024-01-31 13:19 UTC, rubenausinholaglow commented on src/app/crm/(pages)/tasks/components/tableTasks.tsx
> +  const fetchTasks = async (queryString: any, nextPage?: boolean) => {
query string es un string, no un any

2024-01-31 13:19 UTC, rubenausinholaglow commented on src/app/crm/(pages)/tasks/components/tableTasks.tsx
> +  const updateState = (taskData: any, nextPage = false) => {
Nada de anys

2024-01-31 13:19 UTC, rubenausinholaglow commented on src/app/crm/(pages)/tasks/components/tableTasks.tsx
> +      const { data } = await client.query({ query: queryString });
Porque lo metes entre {} el data?

2024-01-31 13:19 UTC, rubenausinholaglow commented on src/app/crm/components/table/Pagination.tsx
> +          if (currentPage === 1) return;
Si ya le pones el disabled abajo esot no hace falt ano?

2024-01-31 13:19 UTC, rubenausinholaglow commented on src/app/crm/components/table/Pagination.tsx
> +          onPageChange(currentPage + 1);
Creo que el orden de estas funciones esta mal, almenos arriba estan al reves y me tiene mas sentido

2024-01-31 13:19 UTC, rubenausinholaglow commented on src/app/crm/components/table/Pagination.tsx
> +          onPageChange(currentPage + 1);
Tampoco entiendo porque tenemos dos funciones, creo que el on page change deberia de hacerlo

2024-01-31 13:27 UTC, JordiPuigdo commented on src/app/crm/(pages)/tasks/components/tableTasks.tsx
> +      const { data } = await client.query({ query: queryString });
Porqué el resultado te devuelve un objeto de tipo ApolloQueryResult<T> y este tiene data, errors, error, loading.. y solo queremos la data

2024-02-01 10:51 UTC, rubenausinholaglow requested changes

2024-02-01 10:51 UTC, rubenausinholaglow commented on src/app/crm/(pages)/tasks/components/tableTasks.tsx
> +    { label: 'Fecha Finzaliación', key: 'completedTime', format: 'date' },
Finalización

2024-02-01 10:51 UTC, rubenausinholaglow commented on src/app/crm/components/table/DataTable.tsx
> +    executeQuery(true, '', 10000, sortedBy);
Que es este 10000?

2024-02-01 10:51 UTC, rubenausinholaglow commented on src/app/crm/components/table/TableFunctions.ts
> +
Quitar enters

2024-02-01 14:02 UTC, rubenausinholaglow approved these changes

2024-02-01 14:02 UTC, merged