Home ssr
rubenausinholaglow/holaglowreact pull request #582
Opened 2024-02-05 14:33 UTC by lltallada

2024-02-05 17:19 UTC, rubenausinholaglow requested changes

2024-02-05 17:19 UTC, rubenausinholaglow commented on src/app/(ssr)/homeSSR/components/FooterSSR.tsx
> +  const { clinics } = useGlobalPersistedStore(state => state);
Esto no deberia salir del store

2024-02-05 17:19 UTC, rubenausinholaglow commented on src/app/(ssr)/homeSSR/components/Header.tsx
> +'use client';
Se me hace muy raro tener aqui un use client solo por tener la funcion setSelectedTreatments... creo que tiene que haber formas mejores de hacer esto

2024-02-05 17:19 UTC, rubenausinholaglow commented on src/app/(ssr)/homeSSR/components/FooterSSR.tsx
> +'use client';
No me cuadra tener aqui un use client

2024-02-05 17:19 UTC, rubenausinholaglow commented on src/app/(ssr)/homeSSR/components/FloatingBottomBar.tsx
> +'use client';
No me cuadra tener un use client en un floating bottom bar. Se que es por el setSelectedTreatments, pero tiene que haber otras formas

2024-02-05 17:19 UTC, rubenausinholaglow commented on src/app/(ssr)/homeSSR/components/ClinicsSelector.tsx
> +'use client';
Porque esto se necesita use client?

2024-02-05 17:19 UTC, rubenausinholaglow commented on src/app/(ssr)/homeSSR/components/HomeProfessionals.tsx
> +            //origin={deviceSize.isMobile ? 'bottom' : 'left'}
Este comentario?

2024-02-05 17:19 UTC, rubenausinholaglow commented on src/app/(ssr)/homeSSR/components/Modal.tsx
> +'use client';
Un modal con use client? Raro

2024-02-05 17:19 UTC, rubenausinholaglow commented on src/app/(ssr)/homeSSR/components/Products.tsx
> +'use client';
Esto porque es use client?

2024-02-05 17:19 UTC, rubenausinholaglow commented on src/app/(ssr)/homeSSR/components/Testimonials.tsx
> +'use client';
Esto porque es use client?

2024-02-12 15:00 UTC, lltallada commented on src/app/(ssr)/homeSSR/components/FooterSSR.tsx
> +  const { clinics } = useGlobalPersistedStore(state => state);
Se ha refactorizado el footer para que sea SSR. Las partes que necesitan hooks son ahora componentes que se importan en el FooterSSR (Accordions + deviceSize)

2024-02-12 15:02 UTC, lltallada commented on src/app/(ssr)/homeSSR/components/Header.tsx
> +'use client';
No es solo por el selectedTreatments, todo el header tiene animación en base al tamaño de la pantalla y el scroll, por lo que tiene que ser client si o si.

2024-02-12 15:33 UTC, lltallada commented on src/app/(ssr)/homeSSR/components/FooterSSR.tsx
> +'use client';
outdatet, migrado a SSR

2024-02-12 15:35 UTC, lltallada commented on src/app/(ssr)/homeSSR/components/ClinicsSelector.tsx
> +'use client';
* El componente Accordion necesita guardarse el estado de si está abierto o no
* Se calcula la altura del mapa en base al dispositivo
* Se genera el mapa en base a la clínica seleccionada por el usuario

2024-02-12 15:35 UTC, lltallada commented on src/app/(ssr)/homeSSR/components/HomeProfessionals.tsx
> +            //origin={deviceSize.isMobile ? 'bottom' : 'left'}
fuera comment

2024-02-12 15:38 UTC, lltallada commented on src/app/(ssr)/homeSSR/components/Modal.tsx
> +'use client';
La modal es un elemento interactivo, el usuario es quien la activa o no.
Necesito guardar el estado de una modal, si está abierta o no. Y luego ese estado se usa para deshabilitar el scroll en el html para evitar el scroll vertical mientras tienes una modal abierta.

2024-02-12 15:39 UTC, lltallada commented on src/app/(ssr)/homeSSR/components/Products.tsx
> +'use client';
outdated, ya no es SSR.

2024-02-12 16:14 UTC, lltallada commented on src/app/(ssr)/homeSSR/components/Testimonials.tsx
> +'use client';
pasado el use client al componente del carousel que tiene interacción

2024-02-13 11:14 UTC, rubenausinholaglow approved these changes

2024-02-13 11:14 UTC, merged