Dev 1025 Whatsapp
rubenausinholaglow/holaglowreact pull request #597
Opened 2024-02-09 09:07 UTC by KevinNCabrera

2024-02-09 11:50 UTC, JordiPuigdo commented on src/app/crm/(pages)/contacts/[id]/ContactDetailPageBase.tsx
> +            Telefono: {contactDetail?.phonePrefix} {contactDetail?.phone}
Teléfono con acento

2024-02-09 11:56 UTC, JordiPuigdo commented on src/app/crm/components/whatsapp/InputWpp.tsx
> +    const agentId = localStorage.getItem('agentId');
No usamos el localstorage, mejor hazlo con Zustand. Si no sabes hacerlo avísame y te lo explico

2024-02-09 11:57 UTC, JordiPuigdo commented on src/app/crm/components/whatsapp/InputWpp.tsx
> +      const res = await fetch(
este fetch que hacer para envíar el whatsapp alomejor lo podemos poner en un sitio compartido por si queremos llamarlo des de otra pantalla. podríamos crear un WhatsappService o añadir la petición a la ContactService

2024-02-09 13:44 UTC, rubenausinholaglow requested changes

2024-02-09 13:44 UTC, rubenausinholaglow commented on src/app/GraphQL/query/ContactDetailQuery.ts
> +export default function getContactDetail(id: string) {
Separar esto en diferentes queries de graphql

2024-02-09 13:44 UTC, rubenausinholaglow commented on src/app/crm/components/whatsapp/InputWpp.tsx
> +      console.error(
Meter un log de bugsnag

2024-02-09 13:44 UTC, rubenausinholaglow commented on src/app/crm/components/whatsapp/InputWpp.tsx
> +        throw new Error('Network response was not OK');
Meter un log de bugsnag

2024-02-13 12:32 UTC, KevinNCabrera commented on src/app/crm/(pages)/contacts/[id]/ContactDetailPageBase.tsx
> +            Telefono: {contactDetail?.phonePrefix} {contactDetail?.phone}
Done!

2024-02-14 13:18 UTC, KevinNCabrera commented on src/app/crm/components/whatsapp/InputWpp.tsx
> +      console.error(
Done!

2024-02-14 13:19 UTC, KevinNCabrera commented on src/app/crm/components/whatsapp/InputWpp.tsx
> +    const agentId = localStorage.getItem('agentId');
Resolved!

2024-02-14 16:57 UTC, rubenausinholaglow commented on src/app/GraphQL/query/ContactDetailQuery.ts
> +export function getContactTasks(id: string) {
Yo renombraria esta funcion a "getContactWithTasks" ya que no devuelves solo ltas tasks sino los datos del contacto

2024-02-14 16:57 UTC, rubenausinholaglow commented on src/app/crm/(pages)/contacts/[id]/ContactDetailPageBase.tsx
> +    event.preventDefault();
Esto porque?

2024-02-14 19:26 UTC, KevinNCabrera commented on src/app/crm/(pages)/contacts/[id]/ContactDetailPageBase.tsx
> +    event.preventDefault();
Esto quedo old es la accion que mandar a guardar un recordatorio

2024-02-14 19:27 UTC, KevinNCabrera commented on src/app/GraphQL/query/ContactDetailQuery.ts
> +export function getContactTasks(id: string) {
Done!

2024-02-15 10:34 UTC, merged