Dev 1110 Subida de imagenes, videos y emojis de whatsapp
rubenausinholaglow/holaglowreact pull request #662
Opened 2024-02-29 14:38 UTC by KevinNCabrera

2024-03-01 07:17 UTC, JordiPuigdo commented on src/app/crm/components/whatsapp/InputWpp.tsx
> +        `https://localhost:7103/Tasks/SendWhatsappFile`,
cuidao localhost??

2024-03-01 08:02 UTC, rubenausinholaglow requested changes

2024-03-01 08:02 UTC, rubenausinholaglow commented on src/app/crm/components/whatsapp/InputWpp.tsx
> +      console.error('Error al subir la imagen:', error);
Bugsnag

2024-03-01 09:05 UTC, KevinNCabrera commented on src/app/crm/components/whatsapp/InputWpp.tsx
> +        `https://localhost:7103/Tasks/SendWhatsappFile`,
Si testeando en mi local sera cambiado

2024-03-04 09:02 UTC, KevinNCabrera commented on src/app/crm/components/whatsapp/InputWpp.tsx
> +      console.error('Error al subir la imagen:', error);
Done!

2024-03-04 09:02 UTC, KevinNCabrera commented on src/app/crm/components/whatsapp/InputWpp.tsx
> +      }
Done!

2024-03-05 07:52 UTC, rubenausinholaglow requested changes

2024-03-05 07:52 UTC, rubenausinholaglow commented on src/app/utils/useAsyncClientGQL.ts
> +const client = createApolloClient("https://localhost:7103/", '');
Revert this

2024-03-05 15:09 UTC, merged