checkout flow redesifn
rubenausinholaglow/holaglowreact pull request #725
Opened 2024-03-25 08:02 UTC by lltallada

2024-03-25 09:28 UTC, rubenausinholaglow requested changes

2024-03-25 09:28 UTC, rubenausinholaglow commented on src/app/(web)/checkout/confirmation/components/AppointmentResume.tsx
> +          {/* <TreatmentName /> */}
Borrar please

2024-03-25 09:28 UTC, rubenausinholaglow commented on src/app/(web)/checkout/confirmation/components/AppointmentResume.tsx
> +                    financiado hasta 18 meses con Pepper o Alma
Creo que aqui deberiamos añadir Frakmenta, confirmalo con Marc porfa

2024-03-25 10:34 UTC, lltallada commented on src/app/(web)/checkout/confirmation/components/AppointmentResume.tsx
> +                    financiado hasta 18 meses con Pepper o Alma
Hablado con Marc, dejamos solo el copy de la financiación. No se meten widgets.

2024-03-25 10:49 UTC, JordiPuigdo submitted a review, later dismissed

2024-03-27 07:53 UTC, lltallada commented on src/app/(web)/checkout/confirmation/components/AppointmentResume.tsx
> +          {/* <TreatmentName /> */}
done!

2024-03-27 08:12 UTC, JordiPuigdo approved these changes

2024-03-27 08:40 UTC, rubenausinholaglow approved these changes

2024-03-27 08:43 UTC, merged