Add filter products by clinic in dashboard
rubenausinholaglow/holaglowreact pull request #737
Opened 2024-03-27 13:53 UTC by JordiPuigdo

2024-03-27 15:10 UTC, rubenausinholaglow requested changes

2024-03-27 15:10 UTC, rubenausinholaglow commented on src/app/(dashboard)/dashboard/(pages)/schedule/page.tsx
> +        const products = data
Podemos meter esto en algun sitio que reaprovechemos y lo llamemos desde aqui y desde mas arriba? :P Quizas dentro del getdashboardproducts?

2024-03-27 15:30 UTC, lltallada submitted a review, later dismissed

2024-03-27 15:50 UTC, rubenausinholaglow approved these changes

2024-04-02 08:19 UTC, lltallada approved these changes

2024-04-04 06:50 UTC, merged