Dev 1283
rubenausinholaglow/holaglowreact pull request #746
Opened 2024-04-09 09:41 UTC by JordiPuigdo

2024-04-11 10:41 UTC, lltallada commented on src/app/(dashboard)/dashboard/(pages)/checkin/treatments/page.tsx
> +            <TreatmentAccordionSelector isDashboard />
el treatment selector pot estar en dos contextos diferents al dash?

2024-04-11 11:04 UTC, rubenausinholaglow requested changes

2024-04-12 08:19 UTC, JordiPuigdo commented on src/app/(dashboard)/dashboard/(pages)/schedule/page.tsx
> +      setIsLoading(false);
Porqué cuando entramos a la página es un setisloading a true, entonces si entra en el set treatments ya tiene el setisloading a false y si entra en el else tenemos este setisloading a false

2024-04-12 08:23 UTC, JordiPuigdo commented on src/app/(dashboard)/dashboard/(pages)/checkin/treatments/page.tsx
> +            <TreatmentAccordionSelector isDashboard />
Ara mateix, no! Perquè el check in no s'utilitza

2024-04-12 09:08 UTC, rubenausinholaglow commented on src/app/(dashboard)/dashboard/(pages)/schedule/page.tsx
> +      setIsLoading(false);
Por eso, este no deberia estar aqui, deberia estar dentro del setpackinproductcart

2024-04-15 06:03 UTC, JordiPuigdo commented on src/app/(dashboard)/dashboard/(pages)/schedule/page.tsx
> +      setIsLoading(false);
El setpackInproductCart es un usestate que solo se pone en true or false

2024-04-15 06:38 UTC, rubenausinholaglow approved these changes

2024-04-16 14:01 UTC, rubenausinholaglow submitted a review, later dismissed

2024-04-16 14:41 UTC, lltallada submitted a review, later dismissed

2024-04-16 14:42 UTC, rubenausinholaglow approved these changes

2024-04-16 14:43 UTC, rubenausinholaglow approved these changes

2024-04-16 14:45 UTC, merged