confirmation copies
rubenausinholaglow/holaglowreact pull request #774
Opened 2024-04-24 14:03 UTC by lltallada

2024-04-26 07:50 UTC, JordiPuigdo approved these changes

2024-04-26 07:50 UTC, JordiPuigdo submitted a review, later dismissed

2024-04-26 07:52 UTC, rubenausinholaglow requested changes

2024-04-26 07:52 UTC, rubenausinholaglow commented on src/app/(web)/checkout/confirmation/components/Confirmation.tsx
> +                  {isProbadorVirtual ? '¡Recibido!' : 'Pago recibido.'}
Creo que en lugar de usar este booleano, deberiamos de mirar si el precio del producto es > 0, porque ahora por ejemplo vamos a permitir el probador virtual online, y esto fallara tambien aqui. Me parece mas robusto mirar el precio del producto

2024-04-26 14:05 UTC, rubenausinholaglow approved these changes

2024-04-29 09:24 UTC, JordiPuigdo approved these changes

2024-04-29 10:09 UTC, rubenausinholaglow approved these changes

2024-04-29 10:09 UTC, merged