Dev 1614 derma output urls
rubenausinholaglow/holaglowreact pull request #852
Opened 2024-05-27 07:38 UTC by lltallada

2024-05-28 12:55 UTC, JordiPuigdo approved these changes

2024-05-28 12:58 UTC, rubenausinholaglow requested changes

2024-05-28 12:58 UTC, rubenausinholaglow commented on src/app/(web)/(derma)/multistep/(output)/output-pictures/page.tsx
> +'use client';
Eset use cient porque si no has tocado nada de dentro?

2024-05-28 12:58 UTC, rubenausinholaglow commented on src/app/(web)/(derma)/multistep/(output)/output-secondary-concern/page.tsx
> +'use client';
Este use client porque si no has tocado nada de dentro

2024-05-28 12:58 UTC, rubenausinholaglow commented on src/app/(web)/(derma)/multistep/(output)/output-skin-care/page.tsx
> +'use client';
Este use client porque si no has tocado nada de dentro

2024-05-28 12:58 UTC, rubenausinholaglow commented on src/app/(web)/(derma)/multistep/(output)/output-skin-color/page.tsx
> +'use client';
Este use client porque si no has tocado nada de dentro

2024-05-28 12:58 UTC, rubenausinholaglow commented on src/app/(web)/(derma)/multistep/(output)/output-skin-type/page.tsx
> +'use client';
Este use client porque si no has tocado nada de dentro

2024-05-29 10:00 UTC, lltallada commented on src/app/(web)/(derma)/multistep/(output)/output-pictures/page.tsx
> +'use client';
@rubenausinholaglow 

Antes todos los feedbacks eran componentes que se importaban dentro del /feedback/page.tsx
Ese padre tenía el 'use client' porque se usaban distintos hooks. Al tenerlo el padre, todos los componentes que descienden son client side y no hacía falta especificarlo.

Ahora, al generar una ruta nueva, tengo que meter ese 'use client' ya que seguimos usando esos hooks, ya sea para recuperar el pain, usar el router.back(), etc...

2024-05-29 10:52 UTC, rubenausinholaglow submitted a review, later dismissed

2024-05-29 11:09 UTC, JordiPuigdo submitted a review, later dismissed

2024-05-29 11:09 UTC, closed without merging