Dev 1608 dashboard agenda reorder
rubenausinholaglow/holaglowreact pull request #878
Opened 2024-06-06 11:05 UTC by lltallada

2024-06-06 11:34 UTC, rubenausinholaglow approved these changes

2024-06-06 11:54 UTC, JordiPuigdo approved these changes

2024-06-06 11:54 UTC, rubenausinholaglow requested changes

2024-06-06 11:54 UTC, rubenausinholaglow commented on src/app/(web)/components/common/TreatmentAccordionSelector.tsx
> +function reorderArray(arr: string[]) {
Quitar esto y reutilizarlo de web

2024-06-11 07:33 UTC, rubenausinholaglow approved these changes

2024-06-11 07:34 UTC, merged