Change confirmation page
rubenausinholaglow/holaglowreact pull request #898
Opened 2024-06-13 16:29 UTC by JordiPuigdo

2024-06-14 07:43 UTC, rubenausinholaglow submitted a review, later dismissed

2024-06-14 07:47 UTC, lltallada approved these changes

2024-06-17 08:37 UTC, rubenausinholaglow requested changes

2024-06-17 08:37 UTC, rubenausinholaglow commented on src/app/(web)/checkout/confirmation/components/AppointmentResume.tsx
> -          <AccordionTrigger className="">
Porque quitamos esto para web tambien?

2024-06-17 08:43 UTC, rubenausinholaglow approved these changes

2024-06-17 13:04 UTC, lltallada approved these changes

2024-06-17 13:09 UTC, rubenausinholaglow approved these changes

2024-06-18 07:10 UTC, lltallada approved these changes

2024-06-18 07:11 UTC, lltallada approved these changes

2024-06-18 07:38 UTC, rubenausinholaglow approved these changes

2024-06-18 07:39 UTC, merged